--- 
meta:
  - charset: 'utf-8'
  - http-equiv: 'X-UA-Compatible'
    content: 'IE=edge,chrome=1'
  - name: 'viewport'
    content: 'width=device-width,initial-scale=1.0'
scripts: []
styles: []
favicons:
  - rel: 'shortcut icon'
    href: '/assets/favicon.ico'
  - rel: 'apple-touch-icon'
    href: '/assets/apple-touch-icon.png'
  - rel: 'apple-touch-icon'
    sizes: '57x57'
    href: '/assets/apple-touch-icon-57x57.png'
  - rel: 'apple-touch-icon'
    sizes: '72x72'
    href: '/assets/apple-touch-icon-72x72.png'
  - rel: 'apple-touch-icon'
    sizes: '114x114'
    href: '/assets/apple-touch-icon-114x114.png'
layout:
  - style: 'background-color: #ebebeb'
    nested: [{class: wrap}, {class: container}, {class: inner}, {class: innermost}]
    rows: 
      - class: row clearfix
        cols: 
          - id: alerts
            template: alerts
#  - id: header
#    rows:
#      - class: container
#        nested: [{class: row}]
#        cols:
#          - id: brand
#            class: span3
#            template: shared/brand
#          - id: menus
#            class: span9
#            rows:
#              - cols:
#                  - call: menus(Settings.home.menus.header)
  - id: content
    class: container
    nested: [{class: row, class: span6 offset3}]
    rows:
      - id: signup
        nested: [{id: signup-inner}]
        call: nine_slice
        template: devise/sessions/new
      - id: push-footer
  - id: footer
    nested: [{class: container}]
    rows:
      - class: row
        cols:
        - class: span12
          nested: [{class: block}]
          html: 'Forbes Hackathon | December 13, 2013'
